name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:          
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-dark.svg?color_snake=#ffffff&color_dots=#161b22,#4d4d4d,#7a7a7a,#b0b0b0,#ffffff
            dist/snake-light.svg?color_snake=#000000&color_dots=#ebedf0,#c6c6c6,#8f8f8f,#4d4d4d,#000000

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
